version: 0.2
env:
  variables:
    SRC_DIR: "github.com/n-someya/lambda-gittrend"
    GO111MODULE: "on"
phases:
  install:
    runtime-versions:
      golang: 1.12
  pre_build:
    commands:
      - echo "Nothing to do"
     # - cd "/go/src/${SRC_DIR}" && go test ./jwtgenerator/ -v
     # - cd "/go/src/${SRC_DIR}" && go test ./config/ -v
  build:
    commands:
     - go build main.go
  post_build:
    commands:
      - aws cloudformation package --template-file cfTemplate.yaml --s3-bucket gittrendlambda --s3-prefix main --output-template-file samTemplate.yaml
artifacts:
  type: zip
  files:
    - cfTemplate.yaml
    - samTemplate.yaml
    - main