version: 0.2
env:
  variables:
    SRC_DIR: "github.com/n-someya/lambda-gittrend"
phases: 
  install:
    commands:
      # AWS Codebuild Go images use /go for the $GOPATH so let's copy our 
      # application source code into that directory structure.
      - go get -u github.com/golang/dep/cmd/dep
  pre_build:
    commands:
      - mkdir -p "/go/src/$(dirname ${SRC_DIR})"
      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/${SRC_DIR}"
      - export GOPATH=/go
      - cd "/go/src/${SRC_DIR}" && dep ensure
      - cd "/go/src/${SRC_DIR}" && go test -v .
  build:
    commands:
     - cd "/go/src/${SRC_DIR}" && GOARCH=amd64 GOOS=linux go build main.go
  post_build: 
    commands: 
      - aws cloudformation package --template-file cfTemplate.yaml --s3-bucket gittrendlambda --s3-prefix main --output-template-file samTemplate.yaml
artifacts: 
  type: zip 
  files: 
    - cfTemplate.yaml 
    - samTemplate.yaml
    - main