AWSTemplateFormatVersion: "2010-09-09"

Transform: 'AWS::Serverless-2016-10-31'
Resources:
  GitTrendLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: ./
      MemorySize: 128
      Role: >-
        arn:aws:iam::848145842635:role/lambda_basic_execution
      Timeout: 90
      Events:
        CheckWebsiteScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)