AWSTemplateFormatVersion: "2010-09-09"

Transform: 'AWS::Serverless-2016-10-31'
Resources:
  App:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: ./
      MemorySize: 128
      Role: >-
        arn:aws:iam::848145842635:role/lambda_basic_execution
      Timeout: 3